/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_smart_ai_InterfaceTest */

#ifndef _Included_cn_smart_ai_InterfaceTest
#define _Included_cn_smart_ai_InterfaceTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_smart_ai_InterfaceTest
 * Method:    init
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_InterfaceTest_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_smart_ai_InterfaceTest
 * Method:    detect
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_smart_ai_InterfaceTest_detect
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
